export const CATEGORIES = [
  {
    name: 'Museum',
    name_nl: 'Museum',
    name_en: 'Museum',
    slug: 'museum',
    icon: '',
    color: '#F97316',
    textColor: '#FFFFFF',
  },
  {
    name: 'Expo',
    name_nl: 'Expo',
    name_en: 'Exhibition',
    slug: 'expo',
    icon: '',
    color: '#A855F7',
    textColor: '#FFFFFF',
  },
  {
    name: 'Galerie',
    name_nl: 'Galerie',
    name_en: 'Gallery',
    slug: 'galerie',
    icon: '',
    color: '#14B8A6',
    textColor: '#FFFFFF',
  },
  {
    name: 'Theater',
    name_nl: 'Theater',
    name_en: 'Theater',
    slug: 'theater',
    icon: '',
    color: '#EC4899',
    textColor: '#FFFFFF',
  },
  {
    name: 'Bioscoop',
    name_nl: 'Bioscoop',
    name_en: 'Cinema',
    slug: 'bioscoop',
    icon: '',
    color: '#0B0B0C',
    textColor: '#FFFFFF',
  },
  {
    name: 'Filmhuis',
    name_nl: 'Filmhuis',
    name_en: 'Movie House',
    slug: 'filmhuis',
    icon: '',
    color: '#7C3AED',
    textColor: '#FFFFFF',
  },
  {
    name: 'Live Muziek',
    name_nl: 'Live Muziek',
    name_en: 'Live Music',
    slug: 'live-muziek',
    icon: '',
    color: '#EF4444',
    textColor: '#FFFFFF',
  },
  {
    name: 'Comedy',
    name_nl: 'Comedy',
    name_en: 'Comedy',
    slug: 'comedy',
    icon: '',
    color: '#F59E0B',
    textColor: '#0B0B0C',
  },
  {
    name: 'Escape Room',
    name_nl: 'Escape Room',
    name_en: 'Escape Room',
    slug: 'escape-room',
    icon: '',
    color: '#5B1020',
    textColor: '#FFFFFF',
  },
  {
    name: 'Arcade',
    name_nl: 'Arcade',
    name_en: 'Arcade',
    slug: 'arcade',
    icon: '',
    color: '#F472B6',
    textColor: '#0B0B0C',
  },
  {
    name: 'VR Experience',
    name_nl: 'VR Experience',
    name_en: 'VR Experience',
    slug: 'vr-experience',
    icon: '',
    color: '#FDE047',
    textColor: '#0B0B0C',
  },
  {
    name: 'Karaoke',
    name_nl: 'Karaoke',
    name_en: 'Karaoke',
    slug: 'karaoke',
    icon: '',
    color: '#22D3EE',
    textColor: '#0B0B0C',
  },
  {
    name: 'Workshop',
    name_nl: 'Workshop',
    name_en: 'Workshop',
    slug: 'workshop',
    icon: '',
    color: '#38BDF8',
    textColor: '#0B0B0C',
  },
  {
    name: 'Restaurant',
    name_nl: 'Restaurant',
    name_en: 'Restaurant',
    slug: 'restaurant',
    icon: '',
    color: '#FB7185',
    textColor: '#0B0B0C',
  },
  {
    name: 'Café',
    name_nl: 'Café',
    name_en: 'Cafe',
    slug: 'cafe',
    icon: '',
    color: '#34D399',
    textColor: '#0B0B0C',
  },
  {
    name: 'Cocktailbar',
    name_nl: 'Cocktailbar',
    name_en: 'Cocktail Bar',
    slug: 'cocktailbar',
    icon: '',
    color: '#F97316',
    textColor: '#FFFFFF',
  },
  {
    name: 'Rooftop Bar',
    name_nl: 'Rooftop Bar',
    name_en: 'Rooftop Bar',
    slug: 'rooftop-bar',
    icon: '',
    color: '#3B82F6',
    textColor: '#FFFFFF',
  },
  {
    name: 'Club',
    name_nl: 'Club',
    name_en: 'Club',
    slug: 'club',
    icon: '',
    color: '#8B5CF6',
    textColor: '#FFFFFF',
  },
  {
    name: 'Park',
    name_nl: 'Park',
    name_en: 'Park',
    slug: 'park',
    icon: '',
    color: '#84CC16',
    textColor: '#0B0B0C',
  },
  {
    name: 'Markt',
    name_nl: 'Markt',
    name_en: 'Market',
    slug: 'markt',
    icon: '',
    color: '#EAB308',
    textColor: '#0B0B0C',
  },
  {
    name: 'Rondvaart',
    name_nl: 'Rondvaart',
    name_en: 'Canal Cruise',
    slug: 'rondvaart',
    icon: '',
    color: '#06B6D4',
    textColor: '#FFFFFF',
  },
  {
    name: 'Stadswandeling',
    name_nl: 'Stadswandeling',
    name_en: 'City Walk',
    slug: 'stadswandeling',
    icon: '',
    color: '#10B981',
    textColor: '#FFFFFF',
  },
  {
    name: 'Wellness',
    name_nl: 'Wellness',
    name_en: 'Wellness',
    slug: 'wellness',
    icon: '',
    color: '#F9A8D4',
    textColor: '#0B0B0C',
  },
  {
    name: 'Boulderen',
    name_nl: 'Boulderen',
    name_en: 'Bouldering',
    slug: 'boulderen',
    icon: '',
    color: '#F97316',
    textColor: '#FFFFFF',
  },
  {
    name: 'Sportactiviteit',
    name_nl: 'Sportactiviteit',
    name_en: 'Sports Activity',
    slug: 'sportactiviteit',
    icon: '',
    color: '#22C55E',
    textColor: '#0B0B0C',
  },
  {
    name: 'Outdoor',
    name_nl: 'Outdoor',
    name_en: 'Outdoor',
    slug: 'outdoor',
    icon: '',
    color: '#16A34A',
    textColor: '#FFFFFF',
  },
  {
    name: 'Kids',
    name_nl: 'Kids',
    name_en: 'Kids',
    slug: 'kids',
    icon: '',
    color: '#60A5FA',
    textColor: '#FFFFFF',
  },
  {
    name: 'Groepsactiviteit',
    name_nl: 'Groepsactiviteit',
    name_en: 'Group Activity',
    slug: 'groepsactiviteit',
    icon: '',
    color: '#2DD4BF',
    textColor: '#0B0B0C',
  },
  {
    name: 'Hidden Gem',
    name_nl: 'Hidden Gem',
    name_en: 'Hidden Gem',
    slug: 'hidden-gem',
    icon: '',
    color: '#A78BFA',
    textColor: '#FFFFFF',
  },
];
