export const STRINGS = {
  nl: {
    home: 'Home',
    categories: 'Ontdek',
    map: 'Map',
    login: 'Account',
    searchPlaceholder: 'Zoek naar parken, musea, escape rooms, arcades, VR...',
    seeAll: 'Bekijk alles',
    top10: 'Top 10 van Lokaly',
    popular: 'Populaire Locaties',
    romantic: 'Romantische Avondjes',
    centerHotspots: 'Hotspots in het Centrum',
    chooseVibe: 'Kies jouw Inspiratie',
    discoverAmsterdam: 'Ontdek Amsterdam',
    discoverSubtitle: 'Vind de perfecte activiteit die past bij jouw plannen. Kies een inspiratie of duik direct in ontdek!',
    allLocationsFor: 'Alle locaties voor',
    results: 'resultaten',
    filterByDistrict: 'Filter op stadsdeel',
    backToDiscovery: '← Terug naar Discovery',
    address: 'Adres',
    visitWebsite: 'BEZOEK WEBSITE',
    share: 'Deel',
    save: 'Opslaan',
    saved: 'Opgeslagen',
    website: 'Website',
    close: 'Sluiten',
    categoriesTitle: 'Ontdek',
    categoriesIntro: 'Browse door alle opties en ontdek wat bij jouw inspiratie past.',
    changeLanguage: 'Taal wijzigen',
    languageLabel: 'Taal',
    closePreview: 'Sluit preview',
    featured: 'Uitgelicht',
    menu: 'Menu',
    openMenu: 'Menu openen',
    closeMenu: 'Sluit menu',
    search: 'Zoeken',
    openSearch: 'Zoeken openen',
    noResults: 'Geen locaties gevonden voor de geselecteerde filters. Probeer iets anders.',
    filters: 'Filters',
    vibes: 'Inspiratie',
    highlightedForYou: 'Uitgelicht voor jou',
    moreInfo: 'MEER INFO',
    platform: 'Platform',
    aboutLokaly: 'Over Lokaly',
    howItWorks: 'Hoe het werkt',
    forOrganizers: 'Voor organisatoren',
    info: 'Informatie',
    privacy: 'Privacy & Cookies',
    terms: 'Algemene voorwaarden',
    contact: 'Contact & support',
    cities: 'Steden',
    amsterdamBeta: 'Amsterdam (beta)',
    soonUtrecht: 'Binnenkort: Utrecht',
    soonRotterdam: 'Binnenkort: Rotterdam',
    footerMadeIn: 'Gemaakt in Amsterdam.',
    allRights: 'Alle rechten voorbehouden.',
    categoryResultsTitle: 'Locaties in ontdek',
    backToCategories: '← Terug naar ontdek',
    mapIntroTitle: 'Ontdek Amsterdam op de kaart',
    mapIntroSubtitle: 'Filter op inspiratie, ontdek of stadsdeel en zie direct waar jouw volgende uitje plaatsvindt.',
    allDistricts: 'Alle stadsdelen',
    allVibes: 'Alle inspiratie',
    allCategories: 'Alle ontdek',
    resultsCountPrefix: '',
    resultsCountSuffix: 'locaties gevonden',
    mapApiWarning: 'De kaart werkt pas als je een geldige Google Maps API key toevoegt in de code.',
    searchResultsFor: 'Zoekresultaten voor',
    searchNoResults: 'Geen matches gevonden. Probeer een andere zoekterm.',
    searchTitle: 'Zoeken',
    typeToSearch: 'Typ om te zoeken...',
    feedback: 'Feedback',
    feedbackTitle: 'Feedback',
    feedbackIntro: 'Loop je ergens tegenaan of heb je een idee om Lokaly beter te maken? Laat het hier weten.',
    feedbackType: 'Type',
    feedbackBug: 'Bug / probleem',
    feedbackIdea: 'Idee / suggestie',
    feedbackEmail: 'E-mail (optioneel)',
    feedbackMessage: 'Bericht',
    feedbackSend: 'Verstuur feedback',
    feedbackSending: 'Versturen…',
    feedbackThanks: 'Dankjewel! Je feedback is ontvangen.',
    feedbackError: 'Oeps — versturen lukt nu even niet. Probeer het later opnieuw.',
  },

  en: {
    home: 'Home',
    categories: 'Discover',
    map: 'Map',
    login: 'Account',
    searchPlaceholder: 'Search parks, museums, escape rooms, arcades, VR...',
    seeAll: 'See all',
    top10: "Lokaly's Top 10",
    popular: 'Popular Locations',
    romantic: 'Romantic Spots',
    centerHotspots: 'City Center Hotspots',
    chooseVibe: 'Choose your Inspiration',
    discoverAmsterdam: 'Discover Amsterdam',
    discoverSubtitle: 'Find the perfect activity for your plans. Choose an inspiration or jump right into discover!',
    allLocationsFor: 'All locations for',
    results: 'results',
    filterByDistrict: 'Filter by district',
    backToDiscovery: '← Back to Discovery',
    address: 'Address',
    visitWebsite: 'VISIT WEBSITE',
    share: 'Share',
    save: 'Save',
    saved: 'Saved',
    website: 'Website',
    close: 'Close',
    categoriesTitle: 'Discover',
    categoriesIntro: 'Browse all options and discover what fits your inspiration.',
    changeLanguage: 'Change language',
    languageLabel: 'Language',
    closePreview: 'Close preview',
    featured: 'Featured',
    menu: 'Menu',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    search: 'Search',
    openSearch: 'Open search',
    noResults: 'No locations found for the selected filters.',
    filters: 'Filters',
    vibes: 'Inspiration',
    highlightedForYou: 'Highlighted for you',
    moreInfo: 'MORE INFO',
    platform: 'Platform',
    aboutLokaly: 'About Lokaly',
    howItWorks: 'How it works',
    forOrganizers: 'For organizers',
    info: 'Information',
    privacy: 'Privacy & Cookies',
    terms: 'Terms & Conditions',
    contact: 'Contact & support',
    cities: 'Cities',
    amsterdamBeta: 'Amsterdam (beta)',
    soonUtrecht: 'Coming soon: Utrecht',
    soonRotterdam: 'Coming soon: Rotterdam',
    footerMadeIn: 'Made in Amsterdam.',
    allRights: 'All rights reserved.',
    categoryResultsTitle: 'Locations in discover',
    backToCategories: '← Back to discover',
    mapIntroTitle: 'Explore Amsterdam on the map',
    mapIntroSubtitle: 'Filter by inspiration, discover or district and see exactly where your next plan takes place.',
    allDistricts: 'All districts',
    allVibes: 'All inspiration',
    allCategories: 'All discover',
    resultsCountPrefix: '',
    resultsCountSuffix: 'locations found',
    mapApiWarning: 'The map will work once you add a valid Google Maps API key in the code.',
    searchResultsFor: 'Search results for',
    searchNoResults: 'No matches found. Try another search.',
    searchTitle: 'Search',
    typeToSearch: 'Start typing to search...',
    feedback: 'Feedback',
    feedbackTitle: 'Feedback',
    feedbackIntro: 'Found an issue or have an idea to improve Lokaly? Share it here.',
    feedbackType: 'Type',
    feedbackBug: 'Bug / issue',
    feedbackIdea: 'Idea / suggestion',
    feedbackEmail: 'Email (optional)',
    feedbackMessage: 'Message',
    feedbackSend: 'Send feedback',
    feedbackSending: 'Sending…',
    feedbackThanks: 'Thanks! Your feedback has been received.',
    feedbackError: 'Oops — sending failed. Please try again later.',
  },
};
