export const VIBES = [
  {
    name: 'Date Night',
    name_nl: 'Date Night',
    name_en: 'Date Night',
    slug: 'date-night',
    icon: '',
    color: '#FB7185',
    textColor: '#0B0B0C',
  },
  {
    name: 'Met de Crew',
    name_nl: 'Met de Crew',
    name_en: 'With the Crew',
    slug: 'met-de-crew',
    icon: '',
    color: '#3B82F6',
    textColor: '#FFFFFF',
  },
  {
    name: 'Family Time',
    name_nl: 'Family Time',
    name_en: 'Family Time',
    slug: 'family-time',
    icon: '',
    color: '#22C55E',
    textColor: '#0B0B0C',
  },
  {
    name: 'Solo Mission',
    name_nl: 'Solo Mission',
    name_en: 'Solo Mission',
    slug: 'solo-mission',
    icon: '',
    color: '#A855F7',
    textColor: '#FFFFFF',
  },
  {
    name: 'Rainy Day',
    name_nl: 'Rainy Day',
    name_en: 'Rainy Day',
    slug: 'rainy-day',
    icon: '',
    color: '#64748B',
    textColor: '#FFFFFF',
  },
  {
    name: 'Na het Werk',
    name_nl: 'Na het Werk',
    name_en: 'After Work',
    slug: 'na-het-werk',
    icon: '',
    color: '#F97316',
    textColor: '#FFFFFF',
  },
  {
    name: 'Weekend Pick',
    name_nl: 'Weekend Pick',
    name_en: 'Weekend Pick',
    slug: 'weekend-pick',
    icon: '',
    color: '#EAB308',
    textColor: '#0B0B0C',
  },
  {
    name: 'Late Night',
    name_nl: 'Late Night',
    name_en: 'Late Night',
    slug: 'late-night',
    icon: '',
    color: '#7C3AED',
    textColor: '#FFFFFF',
  },
  {
    name: 'Easy Going',
    name_nl: 'Easy Going',
    name_en: 'Easy Going',
    slug: 'easy-going',
    icon: '',
    color: '#14B8A6',
    textColor: '#FFFFFF',
  },
  {
    name: 'Actie Aan',
    name_nl: 'Actie Aan',
    name_en: 'Action On',
    slug: 'actie-aan',
    icon: '',
    color: '#EF4444',
    textColor: '#FFFFFF',
  },
  {
    name: 'Culture Fix',
    name_nl: 'Culture Fix',
    name_en: 'Culture Fix',
    slug: 'culture-fix',
    icon: '',
    color: '#4F46E5',
    textColor: '#FFFFFF',
  },
  {
    name: 'Even Opladen',
    name_nl: 'Even Opladen',
    name_en: 'Recharge',
    slug: 'even-opladen',
    icon: '',
    color: '#2DD4BF',
    textColor: '#0B0B0C',
  },
  {
    name: 'Iets Anders',
    name_nl: 'Iets Anders',
    name_en: 'Something Different',
    slug: 'iets-anders',
    icon: '',
    color: '#EC4899',
    textColor: '#FFFFFF',
  },
  {
    name: 'Lekker Spelen',
    name_nl: 'Lekker Spelen',
    name_en: 'Playful',
    slug: 'lekker-spelen',
    icon: '',
    color: '#F59E0B',
    textColor: '#0B0B0C',
  },
  {
    name: 'Impressie Maken',
    name_nl: 'Impressie Maken',
    name_en: 'Impress',
    slug: 'impressie-maken',
    icon: '',
    color: '#0EA5E9',
    textColor: '#FFFFFF',
  },
  {
    name: 'Buitenlucht',
    name_nl: 'Buitenlucht',
    name_en: 'Fresh Air',
    slug: 'buitenlucht',
    icon: '',
    color: '#16A34A',
    textColor: '#FFFFFF',
  },
  {
    name: 'Binnen & Knus',
    name_nl: 'Binnen & Knus',
    name_en: 'Indoor & Cozy',
    slug: 'binnen-knus',
    icon: '',
    color: '#A78BFA',
    textColor: '#FFFFFF',
  },
  {
    name: 'Feestmodus',
    name_nl: 'Feestmodus',
    name_en: 'Party Mode',
    slug: 'feestmodus',
    icon: '',
    color: '#D946EF',
    textColor: '#FFFFFF',
  },
];
